### ISSUE TITLE
Email not recieve

### ISSUE THREAD

**Issue by aymenkssi** [tiagorlampert/sAINT#22]
Hi,
I made the installation on Kali Linux and I generated the jar file but when I tested on the Windows machine I note that the sAINT folder was created but I do not receive the Email despite that I used a gmail email address with the correct password

**Comment by MasterFlomaster1** [comment]
Don't forget to allow access to less secure apps on your google account!

Check here: https://myaccount.google.com/lesssecureapps?pli=1

**Comment by aymenkssi** [comment]
yes i did but without result maybe there is a problem in the smtp.jar file

**Comment by MasterFlomaster1** [comment]
I checked several times today and it works fine for me.

Run the jar file in terminal and check logs. There should be error message.

**Comment by aymenkssi** [comment]
this is the output of the debug 
![debug](https://user-images.githubusercontent.com/25365772/77238540-1ef60d00-6bd1-11ea-900e-86419c0628a1.JPG)

**Comment by MasterFlomaster1** [comment]
Seems like you can't resolve smtp.gmail.com. Try to reinstall smtp.jar

**Comment by aymenkssi** [comment]
Thanks MasterFlomaster1 now it's Ok the problem was in the pc on which i do my tests when i change the pc and used an azure VM all is pass correctly

**Comment by MasterFlomaster1** [comment]
Ok, close this issue then

**Comment by GoogTech** [comment]
> 谢谢MasterFlomaster1现在可以了，问题出在电脑上，当我更换电脑并使用天蓝色的VM时，我在上面进行测试

hey bro please tell me how to resolve it ? thanks a lot.
```
DEBUG SMTP: trying to connect to host "smtp.gmail.com", port 465, isSSL false
Sending the email to the following server failed : smtp.gmail.com:465
```

**Comment by MasterFlomaster1** [comment]
> > 谢谢MasterFlomaster1现在可以了，问题出在电脑上，当我更换电脑并使用天蓝色的VM时，我在上面进行测试
> 
> hey bro please tell me how to resolve it ? thanks a lot.
> 
> ```
> DEBUG SMTP: trying to connect to host "smtp.gmail.com", port 465, isSSL false
> Sending the email to the following server failed : smtp.gmail.com:465
> ```

1) Make sure that you use GMAIL account
2) Check spam
3) Turn off Antivirus/Windows Defender
4) Note that email will be received after a certain number of characters were typed

I have just compiled this program myself and everything works fine

**Comment by GoogTech** [comment]
> > > 谢谢MasterFlomaster1现在可以了，问题出在电脑上，当我更换电脑并使用天蓝色的VM时，我在上面进行测试
> > 
> > 
> > 嘿，兄弟，请告诉我该如何解决？非常感谢。
> > ```
> > DEBUG SMTP: trying to connect to host "smtp.gmail.com", port 465, isSSL false
> > Sending the email to the following server failed : smtp.gmail.com:465
> > ```
> 
> 1. 确保您使用GMAIL帐户
> 2. 检查垃圾邮件
> 3. 关闭防病毒/ Windows Defender
> 4. 请注意，键入一定数量的字符后，将收到电子邮件
> 
> 我自己编译了这个程序，一切正常

thanks bro, let's try again.
