### ISSUE TITLE
error ./configure.sh

### ISSUE THREAD

**Issue by SableRojo** [tiagorlampert/sAINT#29]
When i do ./configure.sh at the final it says :
./configure.sh: line 2: mvn: command not found
./configure.sh: line 3: mvn: command not found
./configure.sh: line 4: mvn: command not found
./configure.sh: line 5: mvn: command not found
./configure.sh: line 6: mvn: command not found
./configure.sh: line 7: mvn: command not found
./configure.sh: line 8: mvn: command not found
./configure.sh: line 9: mvn: command not found
./configure.sh: line 10: mvn: command not found
./configure.sh: line 11: mvn: command not found
./configure.sh: line 12: mvn: command not found
./configure.sh: line 13: mvn: command not found
./configure.sh: line 14: mvn: command not found

What can i do?

**Comment by Nacharuvsko** [comment]
You have to install maven.

**Comment by SableRojo** [comment]
i have to do `pip install maven` ?

**Comment by Nacharuvsko** [comment]
> i have to do `pip install maven` ?

What linux distribution you running?
You should install maven by using your system's packet manager.

**Comment by SableRojo** [comment]
> > i have to do `pip install maven` ?
> What linux distribution you running?
Im doing it on windows but linux created a aplication ( posted in the microsoft store ) that when you put `bash` on a terminal, it convert the terminal into linux
> You should install maven by using your system's packet manager.
like `apt get maven` ? or how do i should do it

**Comment by SableRojo** [comment]
nvm i fixed by myself
