### ISSUE TITLE
I don't get email alerts

### ISSUE THREAD

**Issue by chithone** [tiagorlampert/sAINT#8]
everything works fine, saint folder in AppData, with screenshots and key-logs stored locally but i get don't get them in my mail?

**Comment by tiagorlampert** [comment]
Hello,
Check if you allowed access to less secure apps on your google account.
https://myaccount.google.com/lesssecureapps?pli=1

Or maybe your email or password can be wrong.

**Comment by chithone** [comment]
Thanks, works fine. Guess my email was the issue.

**Comment by MOLOKOmilk** [comment]
Same problem, but access to less sec app is on.
